spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${h2.url}
    driver-class-name: org.h2.Driver
    username: ${h2.username}
    password: ${h2.password}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true #  http://localhost:8080/h2-console
logging:
  level:
    org.flywaydb: debug

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${db.url}
    driver-class-name: org.postgresql.Driver
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.ProgressDialect
    generate-ddl: false
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org.flywaydb: debug